imports:
  - { resource: 'serializer/denormalizers.yml' }

services:
#    gdelre_redmine_api.example:
#        class: Gdelre\RedmineApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
